mysite/blog/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    url(r'^search/$', SearchFormView.as_view(), name='search'),
]

mysite/bookmark/urls.py
from django.conf.urls import url
from .views import BookmarkLV, BookmarkDV

urlpatterns = [
    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from .views import HomeView
from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 아래 인증 URL 3개 추가
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name = 'register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    
    # url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    # url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/photo/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', AlbumLV.as_view(), name='index'),    #/
    url(r'^album/$', AlbumLV.as_view, name='album_list'),   # /album/, same as /
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),   # /album/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),   # /photo/99/
]

mysite/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from tagging.fields import TagField


class Post(models.Model):
    title = models.CharField("TITLE", max_length=50)
    slug = models.SlugField("SLUG", unique = True, help_text = 'one word for title alias.')
    description = models.CharField("DESCRIPTION", max_length=100, blank = True, help_text='simple description text.')
    content = models.TextField("CONTENT")
    create_date = models.DateTimeField("Create Date", auto_now=False, auto_now_add=True)
    modify_date = models.DateTimeField("Modify Date", auto_now=True, auto_now_add=False)
    tag = TagField()

    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=(self.slug,))
        
    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

mysite/bookmark/models.py
from django.db import models

class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank = True, null=True)
    url = models.URLField('url',unique=True)

    def __str__(self):
        return "%s %s" %(self.title, self.url)

mysite/photo/models.py
from django.db import models
from django.urls import reverse
from .fields import ThumbnailImageField


class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank = True)
    
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("photo:album_detail", args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank = True)
    upload_date = models.DateTimeField('Upload Date', auto_now=False, auto_now_add=True)
    
    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("photo:photo_detail", args=(self.id,))

mysite/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

mysite/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

from .models import Post
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

from django.views.generic.edit import FormView
from .forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

class PostLV(ListView):
    model = Post
    template_name = "blog/post_all.html"
    context_object_name = 'posts'
    paginate_by = 2


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'


class TagTV(TemplateView):
    template_name = "tagging/tagging_cloud.html"

class PostTOL(TaggedObjectList):
    model = Post
    template_name = "tagging/tagging_post_list.html"

# FormView
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        schWord = '%s' % self.request.POST['search_word']
        post_list = Post.objects.filter(Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()
        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list
        return render(self.request, self.template_name, context)

mysite/bookmark/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from .models import Bookmark

class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark

mysite/mysite/views.py
from django.views.generic import TemplateView

# 아래 3줄 추가
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy

# Homepage View
class HomeView(TemplateView):
    template_name = "home.html"

# 다음 내용 추가
#  User Creation
class UserCreateView(CreateView):
    template_name='registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = "registration/register_done.html"
    

mysite/photo/views.py
from django.views.generic import ListView, DetailView
from .models import Album, Photo


class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo

mysite/blog/templates/blog/post_all.html
{% extends "base.html" %} 
{% block title %} post_all.html {% endblock title %} {% block content %}
<div id="content">
    <h1>Blog List</h1>
    {% for post in posts %}
    <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
    {{post.modify_date|date:'N d, Y'}}
    <p>{{post.description}}</p>
    {% endfor %}
    <br>

    <div>
        <span>
            {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">Previous Page</a>
            {% endif %} Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">Next Page</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}
post_archive.html
{% endblock title %}

{% block content %}
<div id="content">
    <h1>Post Archives until {% now "N d, Y"%}</h1>
    <ul>
        {% for date in date_list %}
    
        <li style="display:inline;">
    
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year - {{date|date:'Y'}}</a>
        </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{post.date|date:'Y-m-d'}}&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}
post_archive_day.html
{% endblock title %}

{% block content %}
<div id="content">
    <h1>Post Archives for {{day|date:'N d, Y'}}</h1>
    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{post.modify_date|date:'Y-m-d'}}&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}
    

mysite/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}
post_archive_month.html
{% endblock title %}

{% block content %}
<div id="content">
    <h1>Post Archives for {{month|date:'N, Y'}}</h1>
    <div>
        <ul>
            {% for post in object_list %}
            
            <li>
                {{post.modify_date|date:'Y-m-d'}}&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}
post_archive_year.html
{% endblock title %}

{% block content %}
<div id="content">
    <h1>Post Archive for {{year|date:'Y'}}</h1>
    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{date|date:'F'}}</a>
        </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li>
                {{post.modify_date|date:'Y-m-d'}}&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}
post_detail.html
{% endblock title %}

{% block content %}
<div id="content">
    <h2>{{object.title}}</h2>
    <p class="other_posts">
        {% if object.get_previous_by_modify_date %}
        <a href="{{object.get_previous_post.get_absolute_url}}" title='View previous post'>&laquo;--{{object.get_previous_post}}</a>
        {% endif %} {% if object.get_next_by_modify_date %}
        <a href="{{object.get_next_post.get_absolute_url}}" title='View next post'>{{object.get_next_post}}--&raquo;</a>
        {% endif %}
    </p>
    <p id="date">{{object.modify_date|date:'j F Y'}}</p>
    <br>
    <div id="body">
        {{object.content|linebreaks}}
    </div>

    <div>
        <b>TAGS:</b>
        {% load tagging_tags %}
        {% tags_for_object object as tags %}
        {% for tag in tags %}
            <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
        <a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>
    </div>

    <br>
    <div>
        {% load disqus_tags %}
        {% disqus_show_comments %}
    </div>
    {% endblock content %}
</div>

mysite/blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}
post_search.html
{% endblock title %}

{% block content %}
<div id="content">
    <h1>Blog Search</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_table}}
        <input type="submit" value="Submit">
    </form>
    <br><br>
    {% if object_list %}
    {% for post in object_list %}
        <h2><a href="{{post.get_absolute.url}}">{{post.title}}</a></h2>
        {{post.modify_date|date:'N d, Y'}}
        <p>{{post.description}}</p>
    {% endfor %}
    {% elif search_term %}
    <b><i>Search Word({{search_term}}) Not Found</i></b>
    {% endif %}
</div>
{% endblock content %}

mysite/blog/templates/tagging/tagging_cloud.html
{% extends "base.html" %}

{% block title %}
tagging_cloud.html
{% endblock title %}

{% load staticfiles %}
{% block extrastyle %}
{% static "tagging/tag.css" %}
{% endblock extrastyle %}
{% block content %}
<div id="content">
    <h1>Blog Tag Cloud</h1>
    <div class="tag-cloud">
        {% load tagging_tags %}
        {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
        {% for tag in tags %}
            <span class="tag-{{tag.font_size}}">
                <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}} ({{tag.font_size}})</a>
            </span>
        {% endfor %}
    </div>
</div>

{% endblock content %}

mysite/blog/templates/tagging/tagging_post_list.html
{% extends "base.html" %}

{% block title %}
tagging_post_list.html
{% endblock title %}

{% block content %}
<div id="content">
    <h1>Post for tag - {{tag.name}}</h1>
    {% for post in object_list %}
        <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
        {{post.modify_date|date:"N d, Y"}}
        <p>{{post.description}}</p>
    {% endfor %}
</div>
{% endblock content %}

mysite/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}
Django Bookmark Detail
{% endblock title %}

{% block content %}
<div id="content">
    <h1>{{object.title}}</h1>
    <ul>
        <li>URL: <a href="{{object.url}}">{{object.url}}</a></li>
    </ul>
</div>
{% endblock content %}

mysite/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}
Django Bookmark List
{% endblock title %}

{% block content %}
<div id="content">
    <h1>Bookmark List</h1>
    <ul>
        {% for bookmark in object_list %}
        <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark}}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

mysite/mysite/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} Django Web Programming {% endblock title %}</title>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% block extrastyle %}{% endblock extrastyle %}" />
</head>

<body>
    <div id="header">
        <h2 class="maintitle">Easy & Fast Django Web Programming</h2>
        {% if user.is_active %}
        <h4 class="welcome">Welcome, 
            <strong>{% firstof user.get_short_name user.get_username %}</strong> /
            <a href="{% url 'password_change' %}">change Password</a> /
            <a href="{% url 'logout' %}">Logout</a>
        </h4>
        {% else %}
        <h4 class="welcome">Welcome, Anonymous / 
            <a href="{% url 'login' %}">Login</a> /
            <a href="{% url 'register' %}">Register</a> /
        </h4>
        {% endif %}

    </div>
    <div id="menu">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
        <li><a href="{% url 'blog:index' %}">Blog</a></li>
        <li><a href="{% url 'photo:index' %}">Photo</a></li>
        <li><a href="#">Add&bigtriangledown;</a>
            <ul>
                <li><a href="#">Bookmark</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Photo</a></li>
            </ul>
        </li>

        <li><a href="#">Change&bigtriangledown;</a>
            <ul>
                <li><a href="#">Bookmark</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Photo</a></li>
            </ul>
        </li>
        <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
        <li><a href="{% url 'blog:search' %}">Search</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
    </div>
    {% block content %} {% endblock content %}
    {% block footer %} {% endblock footer %}
</body>

</html>

mysite/mysite/templates/home.html
{% extends "base.html" %}

{% block title %}
home.html
{% endblock title %}

{% load staticfiles %}
{% block extrastyle %}
{% static 'css/base.css' %}
{% endblock extrastyle %}

{% block content %}

<div id="content_home">
    <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.png' %}" style="height:256px;"></a>
        <h4 style="margin:0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>
    <table id="applist">
        <tr>
            <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non miporta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
        <tr>
            <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non miporta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
        <tr>
            <td><b><i><a href="#">Photo</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non miporta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; shkim 2018
</div>
{% endblock footer %}

mysite/photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}
album_detail.html
{% endblock title %}

{% load staticfiles %}
{% block extrastyle %}
{% static 'photo/photo.css' %}
{% endblock extrastyle %}

{% block content %}
<div id="content">
    <h2 style="display:inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ ojbect.description }}</i></b>
    <hr>
    <div class="album-detail">
        {% for photo in object.photo_set.all %}
        <div class="album-detail-photo">
            <a href="{{photo.get_absolute_url }}">
                <img src="{{photo.image.thumb_url}}" alt="" class="thumbnail">
            </a>
            <li>{{photo.title}}</li>
            <li>{{photo.upload_date|date:"Y-m-d" }}</li>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

mysite/photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}
album_list.html
{% endblock title %}

{% load staticfiles %}
{% block extrastyle %}
{% static 'photo/photo.css' %}
{% endblock extrastyle %}

{% block content %}
<div id="content">
{% for item in object_list %}
<div class="clear_float">
    <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{item.name}}</a></h2>
    #emsp;<b><i>{{item.description}}</i></b>
<hr>
<div class="album-list">
    {% for photo in item.photo_set.all|slice:":5" %}
    <div class="album-list-photo">
        <a href="{{photo.get_absolute_url}}">
            <img src="{{photo.image.thumb_url}}" alt="" class="thumbnail">
        </a>
    </div>
    {% endfor %}
</div>
{% endfor %}
</div>
{% endblock content %}

mysite/photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}
photo_detail.html
{% endblock title %}

{% load staticfiles %}
{% block extrastyle %}
{% static "photo/photo.css" %}
{% endblock extrastyle %}

{% block content %}
<div id="content">
    <h2>{{object.title}}</h2>
    <table class="photo-detail">
        <tr>
            <td><a href="{{object.image.url}}">
                <img src="{{object.image.url}}" alt="" style="max-width:100%">
            </a></td>
            <td>
                <ul>
                    <li>Photo Description</li>
                    {% if object.description %}
                    <p>{{object.description|linebreaks}}</p>
                    {% else %}
                    <p>(blank)</p>
                    {% endif %}
                    <li>Date Uploaded</li>
                    <p>{{object.upload_date}}</p>
                    <li>Album Name</li>
                    <p><a href="{% url 'photo:album_detail' object.album.id %}">{{object.album.name}}</a></p>
                </ul>
            </td>
        </tr>
    </table>
</div>
{% endblock content %}